#!/usr/bin/env python3

# Prerequisites:
#
# sudo apt-get install git python3 python3-dateutil

import sys

from githistorydata.main import main

if __name__ == "__main__":
    main( sys.argv, sys.stdout, sys.stderr )
