#!/bin/bash

# Commit+author and file
# Unique
# Group by commit+author
# Sort numerically

tail -n +1 \
    | awk -F', ' '{print $1, $3, ", ", $6}' \
    | sort | uniq \
    | awk -F', ' '{arr[$1]++}END{for (a in arr) print arr[a], a}' \
    | sort -n -r

