#!/bin/bash

# commit-id, author, file
# unique
# author-of-commit, num-files-in-commit
# author, num-files
# Group by author, mean-num-files
# Sort numerically

tail -n +1 \
    | awk -F', ' '{print $1, ", ", $3, ", ", $6}' \
    | sort | uniq \
    | awk -F', ' '{arr[$1]++; auth[$1]=$2}END{for (a in arr) print auth[a], ",", arr[a]}' \
    | awk -F', ' '{sum[$1]+=$2;count[$1]++}END{for (a in count) print sum[a]/count[a], a}' \
    | sort -n -r

