#!/bin/bash

# Author and commit id
# Unique
# Group by author
# Sort numerically

tail -n +1 \
    | awk -F', ' '{print $3, ", ", $1}' \
    | sort | uniq \
    | awk -F', ' '{arr[$1]++}END{for (a in arr) print arr[a], a}' \
    | sort -n -r

